CREATE DATABASE website
	TEMPLATE template0
	ENCODING 'utf8'
	LC_COLLATE 'en-GB'
	LC_CTYPE 'en-GB';

\connect website;

CREATE TABLE users (
	user_id TEXT NOT NULL,
	username TEXT NOT NULL,
	is_admin BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY (user_id),
	CONSTRAINT username_required CHECK(username <> ''),
	CONSTRAINT no_whitespace CHECK(username = TRIM(' ' FROM username))
);

CREATE UNIQUE INDEX unique_name ON users(LOWER(username));

CREATE TABLE categories (
	category TEXT NOT NULL,
	PRIMARY KEY (category),
	CONSTRAINT category_required CHECK(category <> ''),
	CONSTRAINT no_whitespace CHECK(category = TRIM(' ' FROM category))
);

CREATE TABLE documents (
	document_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id TEXT,
	last_updated TIMESTAMP(0) NOT NULL DEFAULT NOW(),
	title TEXT NOT NULL,
	category TEXT NOT NULL,
	document JSONB NOT NULL,
	num_attachments SMALLINT NOT NULL,
	likes INTEGER NOT NULL DEFAULT 0,
	awaiting_moderation BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY (document_id, awaiting_moderation),
	CONSTRAINT unique_document UNIQUE (user_id, document, awaiting_moderation),
	FOREIGN KEY (user_id) REFERENCES users ON DELETE SET NULL,
	FOREIGN KEY (category) REFERENCES categories,
	CONSTRAINT title_required CHECK(title <> ''),
	CONSTRAINT no_whitespace CHECK(title = TRIM(' ' FROM title)),
	CHECK(num_attachments >= 0),
	CHECK(likes >= 0)
);

CREATE UNIQUE INDEX unique_title ON documents(user_id, LOWER(title), awaiting_moderation);
CREATE INDEX ON documents(title);
CREATE INDEX ON documents(category);
CREATE INDEX ON documents(likes DESC);

CREATE TABLE keywords (
	document_id BIGINT NOT NULL,
	keyword TEXT NOT NULL,
	awaiting_moderation BOOLEAN NOT NULL DEFAULT true,
	CONSTRAINT keyword_required CHECK(keyword <> ''),
	CONSTRAINT no_whitespace CHECK(keyword = TRIM(' ' FROM keyword))
);

CREATE UNIQUE INDEX unique_keyword ON keywords(document_id, LOWER(keyword));
CREATE INDEX ON keywords(keyword);

CREATE TABLE likes (
	user_id TEXT,
	user_id_hash TEXT NOT NULL,
	document_id BIGINT NOT NULL,
	CONSTRAINT "key" UNIQUE (user_id, user_id_hash, document_id),
	FOREIGN KEY (user_id) REFERENCES users ON DELETE SET NULL,
	CONSTRAINT hash CHECK(user_id IS NULL OR user_id_hash = MD5(user_id))
);

CREATE INDEX ON likes(user_id, document_id);
CREATE INDEX ON likes(user_id_hash);

